const recepies = [
  /*
CHICKEN
*/
  // Strogonoff       DONE
  {
    id: "chicken-strogonoff",
    title: "Chicken Strogonoff",
    category: "lunch/dinner",
    price: 15.99,
    img: "https://www.unileverfoodsolutions.com.br/dam/global-ufs/mcos/SLA/calcmenu/recipes/BR-recipes/chicken-&-other-poultry-dishes/strogonoff-de-frango/main-header.jpg",
    ingredients: [
      "4 boneless chicken breasts, diced",
      "350ml totamo sauce",
      "1 corn niblets can",
      "250g creamcheese",
      "Ketchup",
      "Mostard",
      "Worcestershire sauce",
      "Hickory sticks",
    ],
    steps: [
      "Cook the chicken breast untill all the water from the chicken is drained",
      "Add the tomato sauce and water to the pan. Use 2 units of water for every unit of tomato sauce",
      "Add the corn niblets can",
      "Once it starts boiling, add ketchup, mostard and worcestershire sauce to taste",
      "Cook it for 5-10 min or until the chicken is soft",
      "Mix the creamcheese with a little bit of milk. Whisk the mixture untill dissolved",
      "Turn off the head, add the creamcheese mixture and mix well",
      "Serve the dish over rice and add Hickory Sticks to taste",
    ],
    dificulty: "Easey",
    servings: 4,
    totalTime: "45",
    cookTime: "30",
    prepTime: "15",
    spicy: 0,
    tags: ["Chicken", "Lunch", "Dinner"],
  },
  // Chicken Teryaki      DONE
  {
    id: "chicken-teryaki",
    title: "Chicken Teryaki",
    category: "lunch/dinner",
    img: "https://www.eatwell101.com/wp-content/uploads/2020/10/Instant-Pot-Chicken-Teriyaki-recipe-3.jpg",
    ingredients: [
      "4 boneless chicken breasts",
      "1 teaspoon garlic powder",
      "1 cup soy sauce",
      "1/2 cup water",
      "2/3 cup honey",
      "1/2 cup rice vinegar",
      "3 tablespoons brown or white sugar",
      "3 tablespoons corn starch",
      "Vegetable oil",
    ],
    steps: [
      "Dice the chicken breast into medium-small cubes",
      "In a dish add the soy sauce, water, honey, rice vinegar and sugar. Mix well.",
      "Add vegetable oil to a skillet in medium-high head. Once heated add the chicken and cook untill there's no more water.",
      "Turn heat to low, add the sauce mixture and let it sit for 10-15 min.",
      "If the sauce has not thickened, dissolve 1-3 tablespoons of corn starch in water and add to the skillet. Mix well",
      "Serve with rice. Potato wedges go really well with this recipe.",
    ],
    dificulty: "Easy",
    servings: 4,
    totalTime: "45",
    cookTime: "30",
    prepTime: "15",
    spicy: 0,
    tags: ["Chicken", "Lunch", "Dinner"],
  },
  // Chicken Milanese DONE
  {
    id: "chicken-milanese",
    title: "Chicken Milanese",
    category: "lunch/dinner",
    img: "http://www.saboresajinomoto.com.br/uploads/images/recipes/frango-a-milanesa.jpg",
    ingredients: [
      "4 boneless chicken breasts",
      "3 eggs",
      "Flour",
      "Bread Crumbs",
      "Vegetable oil",
    ],
    steps: [
      "Cut the chicken into thin slices.",
      "In seperate bowls add the eggs, flour and bread crumbs. Wisk the eggs and add salt and pepper.",
      "Dunk both sides of the chicken in the egg mixture, then dregde them in the flour, back to the egg, and then coat both sides in the bread crumbs.",
      "Add enough vegetable oil to cover the chicken slices in a skillet on medium-low heat.",
      "Once the oil is hot, add 1-2 pieces at a time. Flip them once the breading is golden brown.",
      "When both sides are done, transfer the chicken to a plate with paper towel and let it sit.",
      "To serve, add 1 piece of chicken to a plate, with rice. Potato wedges make a great side for this dish.",
    ],
    dificulty: "Medium",
    servings: 6,
    totalTime: "35",
    cookTime: "10",
    prepTime: "25",
    spicy: 0,
    tags: ["Chicken", "Lunch", "Dinner"],
  },
  // Chicken Parmegiana     DONE
  {
    id: "chicken-parmegiana",
    title: "Chicken Parmegiana",
    category: "lunch/dinner",
    img: "https://i.ytimg.com/vi/LmKPPuEI-4o/maxresdefault.jpg",
    ingredients: [
      "4 boneless chicken breasts",
      "3 eggs",
      "Flour",
      "Bread Crumbs",
      "Vegetable oil",
    ],
    steps: [
      "Cut the chicken into thin slices.",
      "In seperate bowls add the eggs, flour and bread crumbs. Wisk the eggs and add salt and pepper.",
      "Dunk both sides of the chicken in the egg mixture, then dregde them in the flour, back to the egg, and then coat both sides in the bread crumbs.",
      "Add enough vegetable oil to cover the chicken slices in a skillet on medium-low heat.",
      "Once the oil is hot, add 1-2 pieces at a time. Flip them once the breading is golden brown.",
      "When both sides are done, transfer the chicken to a plate with paper towel and let it sit.",
      "To serve, add 1 piece of chicken to a plate, with rice. Potato wedges make a great side for this dish.",
    ],
    dificulty: "Medium",
    servings: 6,
    totalTime: "35",
    cookTime: "10",
    prepTime: "25",
    spicy: 0,
    tags: ["Chicken", "Lunch", "Dinner"],
  },
  // Chicken w/ Orange Sauce DONE MISSING IMG
  {
    id: "chicken-orange-sauce",
    title: "Chicken w/ Orange sauce",
    acategory: "lunch/dinner",
    img: "https://www.unileverfoodsolutions.com.br/dam/global-ufs/mcos/SLA/calcmenu/recipes/BR-recipes/chicken-&-other-poultry-dishes/strogonoff-de-frango/main-header.jpg",
    ingredients: [
      "4 boneless chicken breast",
      "400g sliced mozzarella",
      "400g sliced ham or turkey breast",
      "4 large oranges",
      "400g cream cheese",
      "20ml milk",
      "50g butter",
      "Toothpick or BBQ sticks",
    ],
    steps: [
      "Cut the chicken into strips, they should be thin and long.",
      "If the cheese and the ham/turkey breast are much larger than the chicken strip, cut them in half.",
      "Place 1 cheese and 1 ham/turkey on an end of the strip, wrap it tight. Once it's all wrapped, stick a toothpick or BBQ stick trough it. Make sure it's wrapped tightly.",
      "Set the roll asside, repeat for all other strips.",
      "On a skillet melt the butter over a medium-low heat and add the chicken. Let it cook until golden-brown on one side, and flip it using a tong or fork. Make sure all sides are cooked",
      "Remove all the rolls and set them asside. Use a juicer to get the orange juice and remove any seeds from it",
      "In a small container mix the creamcheese with a little bit of milk at a time. It should get to a sour cream consistency.",
      "Add the orange juice and the creamcheese to the skillet, mix well until boiling.",
      "Add the chicken back and make sure all of it gets covered in the sauce. Let it sit on low heat for 5 minutes.",
      "Serve on a plate with rice. Potato wedges go really well as a side.",
    ],
    dificulty: "Medium",
    servings: 6,
    totalTime: "55",
    cookTime: "20",
    prepTime: "35",
    spicy: 0,
    tags: ["Chicken", "Lunch", "Dinner"],
  },
  //   // Pie
  {
    id: "chicken-pie",
    title: "Chicken Pie",
    category: "lunch/dinner",
    img: "http://www.saboresajinomoto.com.br/uploads/images/recipes/torta-de-frango-com-repolho.jpg",
    ingredients: [
      "4 boneless chicken breasts",
      "4 tablespoons vegetable oil",
      "1 can corn",
      "1 can tomato sauce",
      "50g sliced olives",
      "250ml milk",
      "2 eggs",
      "2 cups flour",
      "400g shredded mozzarella",
    ],
    steps: [
      "Cook the chicken in medium-high heat untill soft. Get 2 forks and shredd it. In a pan mix it with the tomato sauce and add the corn, let it cook for 5min",
      "Preheat the oven to 180º C (355º F)",
      "In a blender add the eggs, the milk and half of the cheese, blend it. Slowly add the flower and salt.",
      "In a casserole add half of the blended mixture to the bottom, put the chicken on top and spread cheese on top. Finish with the other half of the mixture on top.",
      "Bake it for 20-30 minutes or until golden-brown.",
      "Let it cool down for 5 minutes. Cut small quares to serve.",
    ],
    dificulty: "Easy",
    servings: 4,
    totalTime: "65",
    cookTime: "30",
    prepTime: "35",
    spicy: 0,
    tags: ["Chicken", "Lunch", "Dinner"],
  },
  // Pancake
  {
    id: "chicken-pancake",
    title: "Chicken Pancake",
    category: "lunch/dinner",
    price: 15.99,
    img: "https://www.unileverfoodsolutions.com.br/dam/global-ufs/mcos/SLA/calcmenu/recipes/BR-recipes/chicken-&-other-poultry-dishes/strogonoff-de-frango/main-header.jpg",
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    ingredients: [
      "4 boneless chicken breasts, diced",
      "350ml totamo sauce",
      "1 corn niblets can",
      "250g creamcheese",
      "Ketchup",
      "Mostard",
      "Worcestershire sauce",
      "Hickory sticks",
    ],
    steps: [
      "Cook the chicken breast untill all the water from the chicken is drained",
      "Add the tomato sauce and water to the pan. Use 2 units of water for every unit of tomato sauce",
      "Add the corn niblets can",
      "Once it starts boiling, add ketchup, mostard and worcestershire sauce to taste",
      "Cook it for 5-10 min or until the chicken is soft",
      "Mix the creamcheese with a little bit of milk. Whisk the mixture untill dissolved",
      "Turn off the head, add the creamcheese mixture and mix well",
      "Serve the dish over rice and add Hickory Sticks to taste",
    ],
    totalTime: "45",
    prepTime: "15",
    cookTime: "30",
    spicy: 0,
    servings: 4,
  },
  //   // Chicken w/ Caramelized Onion
  //   {
  //     id: "chicken-caramelized-onion",
  //     title: "Chicken w/ Caramelized Onion",
  //     category: "lunch/dinner",
  //     price: 15.99,
  //     img: "https://www.unileverfoodsolutions.com.br/dam/global-ufs/mcos/SLA/calcmenu/recipes/BR-recipes/chicken-&-other-poultry-dishes/strogonoff-de-frango/main-header.jpg",
  //     desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  //     ingredients: [
  //       "4 boneless chicken breasts, diced",
  //       "350ml totamo sauce",
  //       "1 corn niblets can",
  //       "250g creamcheese",
  //       "Ketchup",
  //       "Mostard",
  //       "Worcestershire sauce",
  //       "Hickory sticks",
  //     ],
  //     steps: [
  //       "Cook the chicken breast untill all the water from the chicken is drained",
  //       "Add the tomato sauce and water to the pan. Use 2 units of water for every unit of tomato sauce",
  //       "Add the corn niblets can",
  //       "Once it starts boiling, add ketchup, mostard and worcestershire sauce to taste",
  //       "Cook it for 5-10 min or until the chicken is soft",
  //       "Mix the creamcheese with a little bit of milk. Whisk the mixture untill dissolved",
  //       "Turn off the head, add the creamcheese mixture and mix well",
  //       "Serve the dish over rice and add Hickory Sticks to taste",
  //     ],
  //     prepTime: "15 min",
  //     cookTime: "30 min",
  //     spicy: 0,
  //     servings: 4,
  //   },

  //   /*
  // BEEF
  // */
  //   // Hambuger
  //   {
  //     id: "hambueger",
  //     title: "Hamburger",
  //     category: "lunch/dinner",
  //     price: 6.99,
  //     img: "https://makeyourmeals.com/wp-content/uploads/2019/03/air-fryer-hamburger-735x490.jpg",
  //     desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
  //     ingredients: [
  //       "500g ground beef",
  //       "1 teaspoon garlic powder",
  //       "1 cup soy sauce",
  //     ],
  //     steps: [1, 2, 3],
  //     prepTime: "15 min",
  //     cookTime: "30 min",
  //     spicy: 0,
  //     servings: 4,
  //   },

  //   /*
  // PASTA
  // */
  //   // Cheesy Pasta
  //   {
  //     id: "cheesy-pasta",
  //     title: "Cheesy pasta",
  //     category: "lunch/dinner",
  //     price: 6.99,
  //     img: "https://receitatodahora.com.br/wp-content/uploads/2017/08/macarrao-de-panela-de-pressao-simples.jpg",
  //     desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
  //     ingredients: [
  //       "500g corkscrew pasta",
  //       "350ml tomato sauce",
  //       "400g muzzarella cheese (diced or sliced)",
  //       "400g ham or turkey breast (diced or sliced)",
  //       "250g creamcheese",
  //       "Seasoning to taste",
  //     ],
  //     steps: [
  //       "Cook the pasta until desired softness",
  //       "Drain pasta and add the tomato sauce. Use 2 units of water to every unit of sauce",
  //       "Let mixture boil on medium heat",
  //       "Mix the creamcheese with a little bit of milk. Wisk it until dissolved",
  //       "Mix the creamcheese, the cheese and the ham/turkey breask into a bowl",
  //       "Add the pasta to the bowl, mix well",
  //       "Optional: Add shredded mozzarella on top and let it melt",
  //     ],
  //     prepTime: "15 min",
  //     cookTime: "30 min",
  //     spicy: 0,
  //     servings: 4,
  //   },
  //   // Oven Pasta
  //   {
  //     id: "oven-pasta",
  //     title: "Oven Pasta",
  //     category: "lunch/dinner",
  //     price: 15.99,
  //     img: "https://www.unileverfoodsolutions.com.br/dam/global-ufs/mcos/SLA/calcmenu/recipes/BR-recipes/chicken-&-other-poultry-dishes/strogonoff-de-frango/main-header.jpg",
  //     desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  //     ingredients: [
  //       "500g corkscrew pasta",
  //       "350ml tomato sauce",
  //       "400g muzzarella cheese (diced or sliced)",
  //       "400g ham or turkey breast (diced or sliced)",
  //       "250g creamcheese",
  //       "Seasoning to taste",
  //     ],
  //     steps: [
  //       "Cook the chicken breast untill all the water from the chicken is drained",
  //       "Add the tomato sauce and water to the pan. Use 2 units of water for every unit of tomato sauce",
  //       "Add the corn niblets can",
  //       "Once it starts boiling, add ketchup, mostard and worcestershire sauce to taste",
  //       "Cook it for 5-10 min or until the chicken is soft",
  //       "Mix the creamcheese with a little bit of milk. Whisk the mixture untill dissolved",
  //       "Turn off the head, add the creamcheese mixture and mix well",
  //       "Serve the dish over rice and add Hickory Sticks to taste",
  //     ],
  //     prepTime: "15 min",
  //     cookTime: "30 min",
  //     spicy: 0,
  //     servings: 4,
  //   },
  //   // Pasta w/ White Sauce
  //   {
  //     id: "pasta-white-sauce",
  //     title: "Pasta w/ White Sauce",
  //     category: "lunch/dinner",
  //     price: 15.99,
  //     img: "https://www.unileverfoodsolutions.com.br/dam/global-ufs/mcos/SLA/calcmenu/recipes/BR-recipes/chicken-&-other-poultry-dishes/strogonoff-de-frango/main-header.jpg",
  //     desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  //     ingredients: [
  //       "500g corkscrew pasta",
  //       "350ml tomato sauce",
  //       "400g muzzarella cheese (diced or sliced)",
  //       "400g ham or turkey breast (diced or sliced)",
  //       "250g creamcheese",
  //       "Seasoning to taste",
  //     ],
  //     steps: [
  //       "Cook the chicken breast untill all the water from the chicken is drained",
  //       "Add the tomato sauce and water to the pan. Use 2 units of water for every unit of tomato sauce",
  //       "Add the corn niblets can",
  //       "Once it starts boiling, add ketchup, mostard and worcestershire sauce to taste",
  //       "Cook it for 5-10 min or until the chicken is soft",
  //       "Mix the creamcheese with a little bit of milk. Whisk the mixture untill dissolved",
  //       "Turn off the head, add the creamcheese mixture and mix well",
  //       "Serve the dish over rice and add Hickory Sticks to taste",
  //     ],
  //     prepTime: "15 min",
  //     cookTime: "30 min",
  //     spicy: 0,
  //     servings: 4,
  //   },

  //   /*
  // SIDES
  // */
  // Wedges
  {
    id: "potato-wedges",
    title: "Potato Wedges",
    category: "side",
    price: 6.99,
    img: "https://healthyfitnessmeals.com/wp-content/uploads/2020/05/instagram-In-Stream_Square___Baked-potato-wedges-4.jpg",
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
    ingredients: [
      "4 potatoes russet",
      "Paprika, salt, pepper, cumin to taste",
      "Oilive oil",
    ],
    steps: [
      "Wash the potatoes and put it into quarters. If a quarter is too big, cut that in half",
      "Put the cut potatoes into a ziplock bag, add a little bit of olive oil and the spices to taste",
      "Close the bag and mix it well untill all slices of potatoes are seasoned",
      "Get a square casserole and put olive oil ultill the bottom is covered",
      "Add the sliced potatoes to the casserole, avoid putting slices on top of each other",
      "Cook on 250C for 20 minutes",
      "Remove the casserole from the oven, flip the slices over. Now the cooked side should be facing up",
      "Cook for another 20 minutes",
      "Once both sides are cooked and crispy, put them on a plate with paper towel and let it sit for 5 minutes",
      "Add salt and pepper to taste.",
    ],
    totalTime: "45",
    prepTime: "15",
    cookTime: "30",
    spicy: 0,
    servings: 4,
  },
  // Fries
  {
    id: "potato-fries",
    title: "Potato Fries",
    category: "side",
    price: 6.99,
    img: "https://healthyfitnessmeals.com/wp-content/uploads/2020/05/instagram-In-Stream_Square___Baked-potato-wedges-4.jpg",
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
    ingredients: [
      "4 potatoes russet",
      "Paprika, salt, pepper, cumin to taste",
      "Oilive oil",
    ],
    steps: [
      "Wash the potatoes and put it into quarters. If a quarter is too big, cut that in half",
      "Put the cut potatoes into a ziplock bag, add a little bit of olive oil and the spices to taste",
      "Close the bag and mix it well untill all slices of potatoes are seasoned",
      "Get a square casserole and put olive oil ultill the bottom is covered",
      "Add the sliced potatoes to the casserole, avoid putting slices on top of each other",
      "Cook on 250C for 20 minutes",
      "Remove the casserole from the oven, flip the slices over. Now the cooked side should be facing up",
      "Cook for another 20 minutes",
      "Once both sides are cooked and crispy, put them on a plate with paper towel and let it sit for 5 minutes",
      "Add salt and pepper to taste.",
    ],
    totalTime: "45",
    prepTime: "15",
    cookTime: "30",
    spicy: 0,
    servings: 4,
  },
  {
    id: "potato-fries",
    title: "Potato Fries",
    category: "side",
    price: 6.99,
    img: "https://healthyfitnessmeals.com/wp-content/uploads/2020/05/instagram-In-Stream_Square___Baked-potato-wedges-4.jpg",
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
    ingredients: [
      "4 potatoes russet",
      "Paprika, salt, pepper, cumin to taste",
      "Oilive oil",
    ],
    steps: [
      "Wash the potatoes and put it into quarters. If a quarter is too big, cut that in half",
      "Put the cut potatoes into a ziplock bag, add a little bit of olive oil and the spices to taste",
      "Close the bag and mix it well untill all slices of potatoes are seasoned",
      "Get a square casserole and put olive oil ultill the bottom is covered",
      "Add the sliced potatoes to the casserole, avoid putting slices on top of each other",
      "Cook on 250C for 20 minutes",
      "Remove the casserole from the oven, flip the slices over. Now the cooked side should be facing up",
      "Cook for another 20 minutes",
      "Once both sides are cooked and crispy, put them on a plate with paper towel and let it sit for 5 minutes",
      "Add salt and pepper to taste.",
    ],
    totalTime: "45",
    prepTime: "15",
    cookTime: "30",
    spicy: 0,
    servings: 4,
  },
];
export default recepies;
