const recepies = [
  /*
CHICKEN
*/
  // Strogonoff
  {
    id: "chicken-strogonoff",
    title: "Chicken Strogonoff",
    category: "lunch/dinner",
    price: 15.99,
    img: "https://www.unileverfoodsolutions.com.br/dam/global-ufs/mcos/SLA/calcmenu/recipes/BR-recipes/chicken-&-other-poultry-dishes/strogonoff-de-frango/main-header.jpg",
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    ingredients: [
      "4 boneless chicken breasts, diced",
      "350ml totamo sauce",
      "1 corn niblets can",
      "250g creamcheese",
      "Ketchup",
      "Mostard",
      "Worcestershire sauce",
      "Hickory sticks",
    ],
    steps: [
      "Cook the chicken breast untill all the water from the chicken is drained",
      "Add the tomato sauce and water to the pan. Use 2 units of water for every unit of tomato sauce",
      "Add the corn niblets can",
      "Once it starts boiling, add ketchup, mostard and worcestershire sauce to taste",
      "Cook it for 5-10 min or until the chicken is soft",
      "Mix the creamcheese with a little bit of milk. Whisk the mixture untill dissolved",
      "Turn off the head, add the creamcheese mixture and mix well",
      "Serve the dish over rice and add Hickory Sticks to taste",
    ],
    prepTime: "15",
    cookTime: "30",
    totalTime: "45",
    spicy: 0,
    servings: 4,
  },
  // Chicken Teryaki
  {
    id: "chicken-teryaki",
    title: "Chicken Teryaki",
    category: "lunch/dinner",
    price: 13.99,
    img: "https://www.eatwell101.com/wp-content/uploads/2020/10/Instant-Pot-Chicken-Teriyaki-recipe-3.jpg",
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
    ingredients: [
      "4 boneless chicken breasts, diced",
      "1 teaspoon garlic powder",
      "1 cup soy sauce",
      "1/2 cup water",
      "2/3 cup honey",
      "1/2 cup rice vinegar",
      "3 tablespoons corn starch + 3 tablespoons cold water",
    ],
    steps: [1, 2, 3],
    prepTime: "15 min",
    cookTime: "30 min",
    spicy: 0,
    servings: 4,
  },
  // Fried Chicken Brest
  {
    id: "fried-chicken-brest",
    title: "Fried Chicken Brest",
    category: "lunch/dinner",
    price: 15.99,
    img: "https://www.unileverfoodsolutions.com.br/dam/global-ufs/mcos/SLA/calcmenu/recipes/BR-recipes/chicken-&-other-poultry-dishes/strogonoff-de-frango/main-header.jpg",
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    ingredients: [
      "4 boneless chicken breasts, diced",
      "350ml totamo sauce",
      "1 corn niblets can",
      "250g creamcheese",
      "Ketchup",
      "Mostard",
      "Worcestershire sauce",
      "Hickory sticks",
    ],
    steps: [
      "Cook the chicken breast untill all the water from the chicken is drained",
      "Add the tomato sauce and water to the pan. Use 2 units of water for every unit of tomato sauce",
      "Add the corn niblets can",
      "Once it starts boiling, add ketchup, mostard and worcestershire sauce to taste",
      "Cook it for 5-10 min or until the chicken is soft",
      "Mix the creamcheese with a little bit of milk. Whisk the mixture untill dissolved",
      "Turn off the head, add the creamcheese mixture and mix well",
      "Serve the dish over rice and add Hickory Sticks to taste",
    ],
    prepTime: "15 min",
    cookTime: "30 min",
    spicy: 0,
    servings: 4,
  },
  // Parmegiana
  {
    id: "chicken-parmegiana",
    title: "Chicken Parmegiana",
    category: "lunch/dinner",
    price: 15.99,
    img: "https://www.unileverfoodsolutions.com.br/dam/global-ufs/mcos/SLA/calcmenu/recipes/BR-recipes/chicken-&-other-poultry-dishes/strogonoff-de-frango/main-header.jpg",
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    ingredients: [
      "4 boneless chicken breasts, diced",
      "350ml totamo sauce",
      "1 corn niblets can",
      "250g creamcheese",
      "Ketchup",
      "Mostard",
      "Worcestershire sauce",
      "Hickory sticks",
    ],
    steps: [
      "Cook the chicken breast untill all the water from the chicken is drained",
      "Add the tomato sauce and water to the pan. Use 2 units of water for every unit of tomato sauce",
      "Add the corn niblets can",
      "Once it starts boiling, add ketchup, mostard and worcestershire sauce to taste",
      "Cook it for 5-10 min or until the chicken is soft",
      "Mix the creamcheese with a little bit of milk. Whisk the mixture untill dissolved",
      "Turn off the head, add the creamcheese mixture and mix well",
      "Serve the dish over rice and add Hickory Sticks to taste",
    ],
    prepTime: "15 min",
    cookTime: "30 min",
    spicy: 0,
    servings: 4,
  },
  // Chicken w/ Orange Sauce
  //   {
  //     id: "chicken-orange-sauce",
  //     title: "Chicken w/ Orange sauce",
  //     category: "lunch/dinner",
  //     price: 15.99,
  //     img: "https://www.unileverfoodsolutions.com.br/dam/global-ufs/mcos/SLA/calcmenu/recipes/BR-recipes/chicken-&-other-poultry-dishes/strogonoff-de-frango/main-header.jpg",
  //     desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  //     ingredients: [
  //       "4 boneless chicken breasts, diced",
  //       "350ml totamo sauce",
  //       "1 corn niblets can",
  //       "250g creamcheese",
  //       "Ketchup",
  //       "Mostard",
  //       "Worcestershire sauce",
  //       "Hickory sticks",
  //     ],
  //     steps: [
  //       "Cook the chicken breast untill all the water from the chicken is drained",
  //       "Add the tomato sauce and water to the pan. Use 2 units of water for every unit of tomato sauce",
  //       "Add the corn niblets can",
  //       "Once it starts boiling, add ketchup, mostard and worcestershire sauce to taste",
  //       "Cook it for 5-10 min or until the chicken is soft",
  //       "Mix the creamcheese with a little bit of milk. Whisk the mixture untill dissolved",
  //       "Turn off the head, add the creamcheese mixture and mix well",
  //       "Serve the dish over rice and add Hickory Sticks to taste",
  //     ],
  //     prepTime: "15 min",
  //     cookTime: "30 min",
  //     spicy: 0,
  //     servings: 4,
  //   },
  //   // Pie
  //   {
  //     id: "chicken-pie",
  //     title: "Chicken Pie",
  //     category: "lunch/dinner",
  //     price: 15.99,
  //     img: "https://www.unileverfoodsolutions.com.br/dam/global-ufs/mcos/SLA/calcmenu/recipes/BR-recipes/chicken-&-other-poultry-dishes/strogonoff-de-frango/main-header.jpg",
  //     desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  //     ingredients: [
  //       "4 boneless chicken breasts, diced",
  //       "350ml totamo sauce",
  //       "1 corn niblets can",
  //       "250g creamcheese",
  //       "Ketchup",
  //       "Mostard",
  //       "Worcestershire sauce",
  //       "Hickory sticks",
  //     ],
  //     steps: [
  //       "Cook the chicken breast untill all the water from the chicken is drained",
  //       "Add the tomato sauce and water to the pan. Use 2 units of water for every unit of tomato sauce",
  //       "Add the corn niblets can",
  //       "Once it starts boiling, add ketchup, mostard and worcestershire sauce to taste",
  //       "Cook it for 5-10 min or until the chicken is soft",
  //       "Mix the creamcheese with a little bit of milk. Whisk the mixture untill dissolved",
  //       "Turn off the head, add the creamcheese mixture and mix well",
  //       "Serve the dish over rice and add Hickory Sticks to taste",
  //     ],
  //     prepTime: "15 min",
  //     cookTime: "30 min",
  //     spicy: 0,
  //     servings: 4,
  //   },
  //   // Pancake
  //   {
  //     id: "chicken-pancake",
  //     title: "Chicken Pancake",
  //     category: "lunch/dinner",
  //     price: 15.99,
  //     img: "https://www.unileverfoodsolutions.com.br/dam/global-ufs/mcos/SLA/calcmenu/recipes/BR-recipes/chicken-&-other-poultry-dishes/strogonoff-de-frango/main-header.jpg",
  //     desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  //     ingredients: [
  //       "4 boneless chicken breasts, diced",
  //       "350ml totamo sauce",
  //       "1 corn niblets can",
  //       "250g creamcheese",
  //       "Ketchup",
  //       "Mostard",
  //       "Worcestershire sauce",
  //       "Hickory sticks",
  //     ],
  //     steps: [
  //       "Cook the chicken breast untill all the water from the chicken is drained",
  //       "Add the tomato sauce and water to the pan. Use 2 units of water for every unit of tomato sauce",
  //       "Add the corn niblets can",
  //       "Once it starts boiling, add ketchup, mostard and worcestershire sauce to taste",
  //       "Cook it for 5-10 min or until the chicken is soft",
  //       "Mix the creamcheese with a little bit of milk. Whisk the mixture untill dissolved",
  //       "Turn off the head, add the creamcheese mixture and mix well",
  //       "Serve the dish over rice and add Hickory Sticks to taste",
  //     ],
  //     prepTime: "15 min",
  //     cookTime: "30 min",
  //     spicy: 0,
  //     servings: 4,
  //   },
  //   // Chicken w/ Caramelized Onion
  //   {
  //     id: "chicken-caramelized-onion",
  //     title: "Chicken w/ Caramelized Onion",
  //     category: "lunch/dinner",
  //     price: 15.99,
  //     img: "https://www.unileverfoodsolutions.com.br/dam/global-ufs/mcos/SLA/calcmenu/recipes/BR-recipes/chicken-&-other-poultry-dishes/strogonoff-de-frango/main-header.jpg",
  //     desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  //     ingredients: [
  //       "4 boneless chicken breasts, diced",
  //       "350ml totamo sauce",
  //       "1 corn niblets can",
  //       "250g creamcheese",
  //       "Ketchup",
  //       "Mostard",
  //       "Worcestershire sauce",
  //       "Hickory sticks",
  //     ],
  //     steps: [
  //       "Cook the chicken breast untill all the water from the chicken is drained",
  //       "Add the tomato sauce and water to the pan. Use 2 units of water for every unit of tomato sauce",
  //       "Add the corn niblets can",
  //       "Once it starts boiling, add ketchup, mostard and worcestershire sauce to taste",
  //       "Cook it for 5-10 min or until the chicken is soft",
  //       "Mix the creamcheese with a little bit of milk. Whisk the mixture untill dissolved",
  //       "Turn off the head, add the creamcheese mixture and mix well",
  //       "Serve the dish over rice and add Hickory Sticks to taste",
  //     ],
  //     prepTime: "15 min",
  //     cookTime: "30 min",
  //     spicy: 0,
  //     servings: 4,
  //   },

  //   /*
  // BEEF
  // */
  //   // Hambuger
  //   {
  //     id: "hambueger",
  //     title: "Hamburger",
  //     category: "lunch/dinner",
  //     price: 6.99,
  //     img: "https://makeyourmeals.com/wp-content/uploads/2019/03/air-fryer-hamburger-735x490.jpg",
  //     desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
  //     ingredients: [
  //       "500g ground beef",
  //       "1 teaspoon garlic powder",
  //       "1 cup soy sauce",
  //     ],
  //     steps: [1, 2, 3],
  //     prepTime: "15 min",
  //     cookTime: "30 min",
  //     spicy: 0,
  //     servings: 4,
  //   },

  //   /*
  // PASTA
  // */
  //   // Cheesy Pasta
  //   {
  //     id: "cheesy-pasta",
  //     title: "Cheesy pasta",
  //     category: "lunch/dinner",
  //     price: 6.99,
  //     img: "https://receitatodahora.com.br/wp-content/uploads/2017/08/macarrao-de-panela-de-pressao-simples.jpg",
  //     desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
  //     ingredients: [
  //       "500g corkscrew pasta",
  //       "350ml tomato sauce",
  //       "400g muzzarella cheese (diced or sliced)",
  //       "400g ham or turkey breast (diced or sliced)",
  //       "250g creamcheese",
  //       "Seasoning to taste",
  //     ],
  //     steps: [
  //       "Cook the pasta until desired softness",
  //       "Drain pasta and add the tomato sauce. Use 2 units of water to every unit of sauce",
  //       "Let mixture boil on medium heat",
  //       "Mix the creamcheese with a little bit of milk. Wisk it until dissolved",
  //       "Mix the creamcheese, the cheese and the ham/turkey breask into a bowl",
  //       "Add the pasta to the bowl, mix well",
  //       "Optional: Add shredded mozzarella on top and let it melt",
  //     ],
  //     prepTime: "15 min",
  //     cookTime: "30 min",
  //     spicy: 0,
  //     servings: 4,
  //   },
  //   // Oven Pasta
  //   {
  //     id: "oven-pasta",
  //     title: "Oven Pasta",
  //     category: "lunch/dinner",
  //     price: 15.99,
  //     img: "https://www.unileverfoodsolutions.com.br/dam/global-ufs/mcos/SLA/calcmenu/recipes/BR-recipes/chicken-&-other-poultry-dishes/strogonoff-de-frango/main-header.jpg",
  //     desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  //     ingredients: [
  //       "500g corkscrew pasta",
  //       "350ml tomato sauce",
  //       "400g muzzarella cheese (diced or sliced)",
  //       "400g ham or turkey breast (diced or sliced)",
  //       "250g creamcheese",
  //       "Seasoning to taste",
  //     ],
  //     steps: [
  //       "Cook the chicken breast untill all the water from the chicken is drained",
  //       "Add the tomato sauce and water to the pan. Use 2 units of water for every unit of tomato sauce",
  //       "Add the corn niblets can",
  //       "Once it starts boiling, add ketchup, mostard and worcestershire sauce to taste",
  //       "Cook it for 5-10 min or until the chicken is soft",
  //       "Mix the creamcheese with a little bit of milk. Whisk the mixture untill dissolved",
  //       "Turn off the head, add the creamcheese mixture and mix well",
  //       "Serve the dish over rice and add Hickory Sticks to taste",
  //     ],
  //     prepTime: "15 min",
  //     cookTime: "30 min",
  //     spicy: 0,
  //     servings: 4,
  //   },
  //   // Pasta w/ White Sauce
  //   {
  //     id: "pasta-white-sauce",
  //     title: "Pasta w/ White Sauce",
  //     category: "lunch/dinner",
  //     price: 15.99,
  //     img: "https://www.unileverfoodsolutions.com.br/dam/global-ufs/mcos/SLA/calcmenu/recipes/BR-recipes/chicken-&-other-poultry-dishes/strogonoff-de-frango/main-header.jpg",
  //     desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  //     ingredients: [
  //       "500g corkscrew pasta",
  //       "350ml tomato sauce",
  //       "400g muzzarella cheese (diced or sliced)",
  //       "400g ham or turkey breast (diced or sliced)",
  //       "250g creamcheese",
  //       "Seasoning to taste",
  //     ],
  //     steps: [
  //       "Cook the chicken breast untill all the water from the chicken is drained",
  //       "Add the tomato sauce and water to the pan. Use 2 units of water for every unit of tomato sauce",
  //       "Add the corn niblets can",
  //       "Once it starts boiling, add ketchup, mostard and worcestershire sauce to taste",
  //       "Cook it for 5-10 min or until the chicken is soft",
  //       "Mix the creamcheese with a little bit of milk. Whisk the mixture untill dissolved",
  //       "Turn off the head, add the creamcheese mixture and mix well",
  //       "Serve the dish over rice and add Hickory Sticks to taste",
  //     ],
  //     prepTime: "15 min",
  //     cookTime: "30 min",
  //     spicy: 0,
  //     servings: 4,
  //   },

  //   /*
  // SIDES
  // */
  //   // Wedges
  //   {
  //     id: "potato-wedges",
  //     title: "Potato Wedges",
  //     category: "side",
  //     price: 6.99,
  //     img: "https://healthyfitnessmeals.com/wp-content/uploads/2020/05/instagram-In-Stream_Square___Baked-potato-wedges-4.jpg",
  //     desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
  //     ingredients: [
  //       "4 potatoes russet",
  //       "Paprika, salt, pepper, cumin to taste",
  //       "Oilive oil",
  //     ],
  //     steps: [
  //       "Wash the potatoes and put it into quarters. If a quarter is too big, cut that in half",
  //       "Put the cut potatoes into a ziplock bag, add a little bit of olive oil and the spices to taste",
  //       "Close the bag and mix it well untill all slices of potatoes are seasoned",
  //       "Get a square casserole and put olive oil ultill the bottom is covered",
  //       "Add the sliced potatoes to the casserole, avoid putting slices on top of each other",
  //       "Cook on 250C for 20 minutes",
  //       "Remove the casserole from the oven, flip the slices over. Now the cooked side should be facing up",
  //       "Cook for another 20 minutes",
  //       "Once both sides are cooked and crispy, put them on a plate with paper towel and let it sit for 5 minutes",
  //       "Add salt and pepper to taste.",
  //     ],
  //     prepTime: "15 min",
  //     cookTime: "30 min",
  //     spicy: 0,
  //     servings: 4,
  //   },
  //   // Fries
  //   {
  //     id: "potato-fries",
  //     title: "Potato Fried",
  //     category: "side",
  //     price: 6.99,
  //     img: "https://healthyfitnessmeals.com/wp-content/uploads/2020/05/instagram-In-Stream_Square___Baked-potato-wedges-4.jpg",
  //     desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
  //     ingredients: [
  //       "4 potatoes russet",
  //       "Paprika, salt, pepper, cumin to taste",
  //       "Oilive oil",
  //     ],
  //     steps: [
  //       "Wash the potatoes and put it into quarters. If a quarter is too big, cut that in half",
  //       "Put the cut potatoes into a ziplock bag, add a little bit of olive oil and the spices to taste",
  //       "Close the bag and mix it well untill all slices of potatoes are seasoned",
  //       "Get a square casserole and put olive oil ultill the bottom is covered",
  //       "Add the sliced potatoes to the casserole, avoid putting slices on top of each other",
  //       "Cook on 250C for 20 minutes",
  //       "Remove the casserole from the oven, flip the slices over. Now the cooked side should be facing up",
  //       "Cook for another 20 minutes",
  //       "Once both sides are cooked and crispy, put them on a plate with paper towel and let it sit for 5 minutes",
  //       "Add salt and pepper to taste.",
  //     ],
  //     prepTime: "15 min",
  //     cookTime: "30 min",
  //     spicy: 0,
  //     servings: 4,
  //   },
];
export default recepies;
